### ISSUE TITLE
ClassNotFoundException com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory

### ISSUE THREAD

**Issue by chcg** [jenkinsci/JiraTestResultReporter-plugin#157]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04

### Reproduction steps

Happens with jenkins startup with

```
 Failed to load /var/lib/jenkins/org.jenkinsci.plugins.JiraTestResultReporter.JiraTestDataPublisher.xml
java.lang.ClassNotFoundException: com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory
      at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
      at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:64)
      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
Caused: java.lang.NoClassDefFoundError: com/atlassian/httpclient/apache/httpcomponents/DefaultHttpClientFactory
      at PluginClassLoader for JiraTestResultReporter//com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:51)
      at PluginClassLoader for JiraTestResultReporter//com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:36)
      at PluginClassLoader for JiraTestResultReporter//com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42)
      at PluginClassLoader for JiraTestResultReporter//org.jenkinsci.plugins.JiraTestResultReporter.JiraTestDataPublisher$JiraTestDataPublisherDescriptor.readResolve(JiraTestDataPublisher.java:489)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:569)
      at com.thoughtworks.xstream.core.util.SerializationMembers.callReadResolve(SerializationMembers.java:78)
Caused: com.thoughtworks.xstream.converters.ConversionException: Failed calling method
---- Debugging information ----
message             : Failed calling method
cause-exception     : java.lang.NoClassDefFoundError
cause-message       : com/atlassian/httpclient/apache/httpcomponents/DefaultHttpClientFactory
method              : org.jenkinsci.plugins.JiraTestResultReporter.JiraTestDataPublisher$JiraTestDataPublisherDescriptor.readResolve()
class               : org.jenkinsci.plugins.JiraTestResultReporter.JiraTestDataPublisher$JiraTestDataPublisherDescriptor
required-type       : org.jenkinsci.plugins.JiraTestResultReporter.JiraTestDataPublisher$JiraTestDataPublisherDescriptor
converter-type      : hudson.util.RobustReflectionConverter
path                : /org.jenkinsci.plugins.JiraTestResultReporter.JiraTestDataPublisher$JiraTestDataPublisherDescriptor
line number         : 8
version             : 2.462.2
-------------------------------

```

### Expected Results

No ClassNotFoundException

### Actual Results

ClassNotFoundException

### Anything else?

Root cause is in pom.xml

https://github.com/jenkinsci/JiraTestResultReporter-plugin/blob/master/pom.xml#L143-L146

and therefore atlassian-httpclient-library is missing in the hpi file.

**Comment by chcg** [comment]
Similar issue on validate test:

```
 Error while serving .../manage/configSubmit
java.lang.ClassNotFoundException: com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory
Caused: java.lang.NoClassDefFoundError: com/atlassian/httpclient/apache/httpcomponents/DefaultHttpClientFactory
      at PluginClassLoader for JiraTestResultReporter//com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:51)
      at PluginClassLoader for JiraTestResultReporter//com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:36)
      at PluginClassLoader for JiraTestResultReporter//com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42)
      at PluginClassLoader for JiraTestResultReporter//org.jenkinsci.plugins.JiraTestResultReporter.JiraTestDataPublisher$JiraTestDataPublisherDescriptor.configure(JiraTestDataPublisher.java:539)
      at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:4109)
      at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:4073)
      at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
      at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:416)
Caused: java.lang.reflect.InvocationTargetException
      at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:420)
      at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:429)
      at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:211)
      at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:37)
      at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)
      at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)
      at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:138)
      at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:644)
      at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:61)
      at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:827)
      at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
      at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:898)
      at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
      at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:548)
      at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:827)
      at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
      at org.kohsuke.stapler.Stapler.invoke(Stapler.java:747)
      at org.kohsuke.stapler.Stapler.service(Stapler.java:253)
      at Jenkins Main ClassLoader//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
      at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
      at Jenkins Main ClassLoader//
...
```
